services:
  simulation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../results:/workspace/results
    command: ["/workspace/scripts/run_experiments.sh", "--skip-sim-build"]
    environment:
      - OMNETPP_IMAGE_VERSION=6.0

volumes:
  results:
